---
version: '3.7'

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_PREFIX}.0/24
          gateway: ${SUBNET_PREFIX}.1

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-03-13T19-46-17Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: asd
    MINIO_ROOT_PASSWORD: asdasdasd
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio1:
    <<: *minio-common
    networks:
      default:
        ipv4_address: ${SUBNET_PREFIX}.2
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    networks:
      default:
        ipv4_address: ${SUBNET_PREFIX}.4
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    networks:
      default:
        ipv4_address: ${SUBNET_PREFIX}.8
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    networks:
      default:
        ipv4_address: ${SUBNET_PREFIX}.16
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    networks:
      default:
        ipv4_address: ${SUBNET_PREFIX}.86
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  buckets:
    image: minio/mc
    hostname: buckets
    entrypoint: >
      /bin/sh -ec '
        for RETRY in 9 8 7 6 5 4 3 2 1 0; do
          sleep 1;
          if /usr/bin/mc config host add minio http://nginx:9000 asd asdasdasd; then
            break;
          fi;
        done && [ $$RETRY -gt 0 ];
        for RETRY in 9 8 7 6 5 4 3 2 1 0; do
          sleep 1;
          if /usr/bin/mc mb --ignore-existing minio/backups; then
            break;
          fi;
        done && [ $$RETRY -gt 0 ];
      '
    depends_on:
      - nginx
