---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
      service: nginx1
  template:
    metadata:
      labels:
        app: nginx1
        service: nginx1
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      containers:
        - name: nginx1
          image: nginx:alpine
          ports:
            - containerPort: 80
