---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.13.2
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: false
        subjectAltNames:
          - dns: kibana-kb-http.eck.svc
          - dns: kibana-kb-http.eck.svc.cluster.local
  elasticsearchRef:
    name: elasticsearch
