---

- assert:
    that:
      - kubernetes_version is defined
      - kubernetes_version is string
      - kubernetes_version | length > 0


- delegate_to: "{{ delegate_to }}"
  delegate_facts: true
  block:
    - include_tasks: "{{ ansible_os_family | lower }}/upgrade-kubeadm.yml"

    - shell: |
        set -o errexit -o pipefail
        kubectl drain {{ ansible_fqdn }} \
          --ignore-daemonsets \
          --delete-local-data \
        |& tee -a /tmp/kubectl.log
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - block:
        - shell: |
            set -o errexit -o pipefail
            kubeadm upgrade node |& tee -a /tmp/kubeadm.log
          args:
            executable: /bin/bash
      rescue:
        - shell: |
            set -o errexit -o pipefail
            kubeadm upgrade node experimental-control-plane |& tee -a /tmp/kubeadm.log
          args:
            executable: /bin/bash

    - include_tasks: "{{ ansible_os_family | lower }}/upgrade-binaries.yml"

    - shell: |
        set -o errexit -o pipefail
        kubectl uncordon {{ ansible_fqdn }} |& tee -a /tmp/kubectl.log
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

# vim:ts=2:sw=2:et:syn=yaml:
