---

- assert:
    that:
      - kubernetes_version is defined
      - kubernetes_version is string
      - kubernetes_version | length > 0

- include_tasks: upgrade-master0.yml

- include_tasks: upgrade-masterN.yml
  loop_control:
    loop_var: destination_master
  loop: "{{ groups.master[1:] }}"  # excluding first master

- include_tasks: upgrade-nodeN.yml
  loop_control:
    loop_var: destination_node
  loop: "{{ groups.node }}"

# vim:ts=2:sw=2:et:syn=yaml:
