---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cpuhog.fullname" . }}
  labels:
    app: &app {{ template "cpuhog.name" . }}
    release: &release {{ .Release.Name }}
    chart: {{ template "cpuhog.chart" . }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      protocol: TCP
      name: http
  selector:
    app: *app
    release: *release
# vim:ts=2:sw=2:et:syn=yaml:
