---
version: "2"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_PREFIX}.0/24
          gateway: ${SUBNET_PREFIX}.1

services:
  traefik:
    image: traefik:2.3
    networks:
      default:
        aliases:
          - traefik.${DOMAIN}
        ipv4_address: ${SUBNET_PREFIX}.4
    extra_hosts: &extra_hosts
      - test1.${DOMAIN}:${SUBNET_PREFIX}.4
      - test2.${DOMAIN}:${SUBNET_PREFIX}.4
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.network=${COMPOSE_PROJECT_NAME}_default
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80

  nginx1:
    image: &nginx_image nginx:1.19-alpine
    networks:
      default:
        aliases:
          - nginx1.${DOMAIN}
        ipv4_address: ${SUBNET_PREFIX}.10
    extra_hosts: *extra_hosts
    labels: &nginx_labels
      - traefik.enable=true
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_default
      - traefik.http.routers.nginx.entrypoints=web
      - traefik.http.routers.nginx.rule=HostRegexp(`{subdomain:[a-z0-9]+}.${DOMAIN}`)
      - traefik.http.services.nginx.loadbalancer.server.port=80

  nginx2:
    image: *nginx_image
    networks:
      default:
        aliases:
          - nginx2.${DOMAIN}
        ipv4_address: ${SUBNET_PREFIX}.20
    extra_hosts: *extra_hosts
    labels: *nginx_labels
