---
- set_fact:
    jobs_dir: "/opt/jobs-{{ inventory_hostname_short }}"

- file:
    path: "{{ jobs_dir }}/"
    state: directory

- copy:
    dest: "{{ jobs_dir }}/nginx.hcl"
    content: |
      job "nginx" {
        region = "global"
        datacenters = ["dc1"]
        type = "service"
        update {
          stagger      = "30s"
          max_parallel = 2
        }
        group "nginx" {
          count = 3
          network {
            port "http" {
              static = 80
            }
          }
          service {
            port = "http"
            check {
              type     = "http"
              path     = "/"
              interval = "10s"
              timeout  = "2s"
            }
          }
          task "frontend" {
            driver = "docker"
            config {
              image = "nginx"
            }
            resources {
              cpu    = 500 # MHz
              memory = 128 # MB
            }
          }
        }
      }

- command: |
    nomad job run "{{ jobs_dir }}/nginx.hcl"
