groups:
  - name: ASD
    rules:
      - alert: AsdUp
        expr: asd_up == 0
        for: 10s
        annotations:
          title: 'asd {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 10 seconds'
        labels: { severity: critical }
