---
- hosts: a1a:a1b
  gather_facts: true
  gather_subset: [min, network]
  tasks: []

- hosts: a1b
  tasks:
    - import_tasks:
        file: "{{ playbook_dir }}/nginx.yml"
      tags: [nginx]

    - import_tasks:
        file: "{{ playbook_dir }}/lvsdr.yml"
      tags: [lvsdr]

- hosts: a1a
  tasks:
    - import_tasks:
        file: "{{ playbook_dir }}/haproxy.yml"
      tags: [haproxy]

    - import_tasks:
        file: "{{ playbook_dir }}/keepalived.yml"
      tags: [keepalived]

    - import_tasks:
        file: "{{ playbook_dir }}/failover.yml"
      tags: [failover]
