---

- hosts: master:node
  gather_facts: true
  pre_tasks: []

- hosts: master:node
  roles:
    - role: deploy/prereq
  tags: [prereq]

- hosts: master
  roles:
    - role: deploy/master
  tags: [deploy]

- hosts: node
  roles:
    - role: deploy/node
  tags: [deploy]

# vim:ts=2:sw=2:et:syn=yaml:
