---

- hosts: master:node
  gather_facts: true
  roles:
    - role: deploy/prereq
      tags: [prereq]

    - when: inventory_hostname in groups.master
      role: deploy/master
      tags: [deploy]

    - when: inventory_hostname in groups.node
      role: deploy/node
      tags: [deploy]

# vim:ts=2:sw=2:et:syn=yaml:
