---

- hosts: master:node
  gather_facts: true
  pre_tasks: []

- hosts: master
  roles:
    - role: upgrade/prereq
  tags: [prereq]

- hosts: master[0]
  roles:
    - role: upgrade/all
  vars_files:
    - roles/upgrade/prereq/defaults/main.yml
  tags: [upgrade]

# vim:ts=2:sw=2:et:syn=yaml:
