---
jobs:

- script: |
    pipelineJob('jenkins3') {
      definition {
        cpsScm {
          scm {
            git {
              remote { url('https://github.com/sk4zuzu/RESEARCH.git') }
              branches('jenkins')
              scriptPath('jenkins_research/jenkins3/Jenkinsfile')
              extensions { }
            }
          }
        }
      }
    }
