---
- hosts: opennebula[0]:kvm:firecracker:lxc
  module_defaults: &module_defaults
    shell: { executable: /bin/bash }
  environment: &environment
    DEBIAN_FRONTEND: noninteractive
  gather_facts: true
  tasks: []

- hosts: opennebula[0]:kvm:firecracker:lxc
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - shell: |
        set -o errexit -o pipefail
        curl -fsSL https://downloads.opennebula.io/repo/repo2.key | apt-key add -

    - copy:
        dest: /etc/apt/sources.list.d/opennebula.list
        content: |
          deb https://{{ ee_token }}@enterprise.opennebula.io/repo/{{ ee_version }}/Ubuntu/{{ ubuntu_version | default('20.04') }} stable opennebula

    - shell: |
        set -o errexit
        apt-get -q update -y

- hosts: opennebula[0]
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - shell: |
        set -o errexit
        apt-get -q install -y mariadb-server
        systemctl start mariadb.service

    - shell: |
        set -o errexit
        mysql -u root <<< "CREATE DATABASE IF NOT EXISTS opennebula CHARACTER SET utf8 COLLATE utf8_general_ci;"
        mysql -u root <<< "GRANT ALL PRIVILEGES ON *.* TO 'oneadmin'@'%' IDENTIFIED BY 'asd';"
        mysql -u root <<< "GRANT ALL PRIVILEGES ON *.* TO 'oneadmin'@'localhost' IDENTIFIED BY 'asd';"
        mysql -u root <<< "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;"

- hosts: opennebula[0]
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - shell: |
        set -o errexit
        apt-get -q install -y docker.io

    - shell: |
        set -o errexit
        apt-get -q install -y opennebula{,-flow,-gate,-provision,-rubygems,-sunstone}
        {% if ee_version is version('6.0', '>=') %}
        apt-get -q install -y opennebula-fireedge
        {% endif %}

    - user:
        name: oneadmin
        groups: [docker]
        append: true

    - user:
        name: one
        home: /home/one
        shell: /bin/bash
        system: false

    - shell: |
        set -o errexit
        if ! grep '^oneadmin:asd$' {{ item.home }}/.one/one_auth; then
          install -o {{ item.owner }} -g {{ item.group }} -m u=rwx,g=rx,o= -d {{ item.home }}/.one/
          install -o {{ item.owner }} -g {{ item.group }} -m u=rw,g=r,o= /dev/fd/0 {{ item.home }}/.one/one_auth <<< 'oneadmin:asd'
        fi
      loop:
        - { owner: oneadmin, group: oneadmin, home: /var/lib/one/ }
        - { owner: one     , group: one     , home: /home/one/    }

    - environment:
        DB: |
          DB = [ BACKEND = "mysql",
                 SERVER  = "localhost",
                 PORT    = 0,
                 USER    = "oneadmin",
                 PASSWD  = "asd",
                 DB_NAME = "opennebula" ]
      shell: |
        set -o errexit
        gawk -i inplace -v DB="$DB" -f- /etc/one/oned.conf <<'EOF'
        /^DB = /,/^\]/ { next }
        { print }
        END { print DB >>FILENAME }
        EOF

    - vars: { _endpoint: "http://{{ one_host | default(ansible_host) }}:5030" }
      shell: |
        set -o errexit
        gawk -i inplace -f- /etc/one/oned.conf <<'EOF'
        BEGIN { update = "ONEGATE_ENDPOINT = \"{{ _endpoint }}\"" }
        /^#*ONEGATE_ENDPOINT[^=]*=/ { $0 = update; found = 1 }
        { print }
        END { if (!found) print update >>FILENAME }
        EOF

    - vars: { _endpoint: "http://{{ one_host | default(ansible_host) }}:2616" }
      shell: |
        set -o errexit
        gawk -i inplace -f- /etc/one/sunstone-server.conf <<'EOF'
        BEGIN { update = ":public_fireedge_endpoint: {{ _endpoint }}" }
        /^#*:public_fireedge_endpoint:/ { $0 = update; found = 1 }
        { print }
        END { if (!found) print update >>FILENAME }
        EOF

    - vars: { _endpoint: "0.0.0.0" }
      shell: |
        set -o errexit
        gawk -i inplace -f- '{{ item }}' <<'EOF'
        BEGIN { update = ":host: {{ _endpoint }}" }
        /^#*:host:/ { $0 = update; found = 1 }
        { print }
        END { if (!found) print update >>FILENAME }
        EOF
      loop:
        - /etc/one/oneflow-server.conf
        - /etc/one/onegate-server.conf

    - vars: { _endpoint: "{{ one_host | default(ansible_host) }}" }
      shell: |
        set -o errexit
        gawk -i inplace -f- /etc/one/monitord.conf <<'EOF'
        BEGIN { update = "MONITOR_ADDRESS = \"{{ _endpoint }}\"," }
        /^NETWORK = /,/^\]/ { if ($1 == "MONITOR_ADDRESS") $0 = update }
        { print }
        EOF

    - shell: |
        set -o errexit
        systemctl enable opennebula{,-flow,-gate,-sunstone}
        systemctl restart opennebula{,-flow,-gate,-sunstone}
        {% if ee_version is version('6.0', '>=') %}
        systemctl enable opennebula-fireedge
        systemctl restart opennebula-fireedge
        {% endif %}

- hosts: opennebula[0]
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - shell: |
        set -o errexit
        cat >/tmp/ds1 <<'EOF'
        DS_MAD    = "fs"
        TM_MAD    = "qcow2"
        SAFE_DIRS = "/var/lib/one/datastores/img/"
        EOF
        onedatastore update 1 /tmp/ds1

    - shell: |
        set -o errexit
        cat >/tmp/ds0 <<'EOF'
        TM_MAD = "qcow2"
        EOF
        onedatastore update 0 /tmp/ds0

    - shell: |
        set -o errexit
        gawk -i inplace -f- /var/lib/one/remotes/etc/vmm/kvm/kvmrc <<'EOF'
        BEGIN { update = "MIGRATE_OPTIONS=--unsafe" }
        /^#*MIGRATE_OPTIONS=/ { $0 = update; found = 1 }
        { print }
        END { if (!found) print update >>FILENAME }
        EOF

- hosts: kvm
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - shell: |
        set -o errexit
        {% if ee_version is version('6.0', '>=') %}
        apt-get -q install -y uuid-runtime opennebula-node-kvm
        {% else %}
        apt-get -q install -y uuid-runtime opennebula-node
        {% endif %}

    - shell: |
        set -o errexit
        gawk -i inplace -f- /etc/libvirt/libvirtd.conf <<'EOF'
        BEGIN { "uuidgen" | getline uuid; update = "host_uuid = \"" uuid "\"" }
        /^#*host_uuid = "00000000-0000-0000-0000-000000000000"/ { $0 = update; found = 1 }
        { print }
        END { if (!found) print update >>FILENAME }
        EOF

    - shell: |
        set -o errexit
        systemctl restart libvirtd
        if virsh net-dumpxml default; then
          virsh net-destroy default
          virsh net-undefine default
        fi

- hosts: lxc
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - shell: |
        set -o errexit
        apt-get -q install -y opennebula-node-lxc

- hosts: firecracker
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - shell: |
        set -o errexit
        apt-get -q install -y opennebula-node-firecracker

- hosts: opennebula[0]
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - shell: |
        set -o errexit
        cat >/tmp/vnet_service <<'EOF'
        NAME   = "service"
        VN_MAD = "bridge"
        BRIDGE = "br0"
        AR = [
          TYPE = "IP4",
          IP   = "{{ public_cidr | nthhost(200) }}",
          SIZE = "48" ]
        NETWORK_ADDRESS = "{{ public_cidr | ipaddr('network') }}"
        NETWORK_MASK    = "{{ public_cidr | ipaddr('netmask') }}"
        GATEWAY         = "{{ public_cidr | nthhost(1) }}"
        DNS             = "1.1.1.1"
        EOF
        onevnet show "service" || onevnet create /tmp/vnet_service

    - shell: |
        set -o errexit
        cat >/tmp/vnet_private <<'EOF'
        NAME   = "private"
        VN_MAD = "bridge"
        BRIDGE = "br1"
        PHYDEV = "eth1"
        AR = [
          TYPE = "IP4",
          IP   = "{{ private_cidr | nthhost(100) }}",
          SIZE = "100" ]
        NETWORK_ADDRESS = "{{ private_cidr | ipaddr('network') }}"
        NETWORK_MASK    = "{{ private_cidr | ipaddr('netmask') }}"
        DNS             = "1.1.1.1"
        EOF
        onevnet show "private" || onevnet create /tmp/vnet_private

    - shell: |
        set -o errexit
        cat >/tmp/user_oneadmin <<'EOF'
        SSH_PUBLIC_KEY = "{{ ssh_public_key }}"
        EOF
        oneuser update oneadmin -a /tmp/user_oneadmin

    - shell: |
        set -o errexit
        onemarketapp export 'Alpine Linux 3.14' alpine314 --datastore default || true
        cat >/tmp/alpine314 <<'EOF'
        NIC = [
          NETWORK_ID      = "0",
          SECURITY_GROUPS = "0" ]
        EOF
        onetemplate update -a alpine314 /tmp/alpine314

- hosts: opennebula[0]
  module_defaults: *module_defaults
  environment: *environment
  pre_tasks:
    - authorized_key:
        user: "{{ item }}"
        key: "{{ ssh_public_key }}"
        state: present
      loop:
        - oneadmin
        - one

    - copy:
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: u=rw,go=
        content: |
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
      loop:
        - { dest: /var/lib/one/.ssh/config, owner: oneadmin, group: oneadmin }
        - { dest: /root/.ssh/config       , owner: root    , group: root     }

    - copy:
        dest: /root/.ssh/id_rsa
        src: /var/lib/one/.ssh/id_rsa
        remote_src: true
        mode: u=rw,go=

- hosts: opennebula[0]
  module_defaults: *module_defaults
  environment: *environment
  tasks:
    - slurp:
        src: /var/lib/one/.ssh/id_rsa.pub
      register: slurp_id_rsa_pub

    - authorized_key:
        user: oneadmin
        key: "{{ slurp_id_rsa_pub.content | b64decode }}"
        state: present
      delegate_to: "{{ item }}"
      loop: >-
        {{ (groups.kvm         | default([]))
         + (groups.lxc         | default([]))
         + (groups.firecracker | default([])) }}

    - shell: |
        set -o errexit
        {% for host in (groups.kvm | default([])) %}
        onehost show {{ host }} || onehost create {{ host }} -i kvm -v kvm
        {% endfor %}

    - shell: |
        set -o errexit
        {% for host in (groups.lxc | default([])) %}
        onehost show {{ host }} || onehost create {{ host }} -i lxc -v lxc
        {% endfor %}

    - shell: |
        set -o errexit
        {% for host in (groups.firecracker | default([])) %}
        onehost show {{ host }} || onehost create {{ host }} -i firecracker -v firecracker
        {% endfor %}
