---

- copy:
    dest: /etc/default/nfs-common
    content: |
      NEED_GSSD="no"

- file:
    path: /shared/
    mode: ugo=rwx
    state: directory

- mount:
    fstype: nfs4
    opts: sec=sys
    src: "{{ hostvars[groups.nfs4_server.0].ansible_facts[WIREGUARD_IF].ipv4.address }}:/shared"
    path: /shared/
    state: mounted

# vim:ts=2:sw=2:et:syn=yaml:
