#!/usr/bin/env groovy

node('agent1 || agent2') {
    stage('asd') {
        sh 'uname -a'
        print "NODE_NAME = ${env.NODE_NAME}"
    }
}

def JOBS = [ 'job1', 'job2', 'job3' ]

node('agents') {
    stage('s1') {
        sh 'uname -a'
        print "s1: NODE_NAME = ${env.NODE_NAME}"

        JOBS.each { job ->
            node('agents') {
                stage(job) {
                    sh 'uname -a'
                    print "${job}: NODE_NAME = ${env.NODE_NAME}"
                }
            }
        }
    }
}
