#!/usr/bin/env groovy

node('agent1 || agent2') {
    stage('asd') {
        sh 'uname -a'
        print "NODE_NAME = ${env.NODE_NAME}"
    }
}

node('agents') {
    stage('s1') {
        sh 'uname -a'
        print "s1: NODE_NAME = ${env.NODE_NAME}"

        node('agents') {
            stage('s2') {
                sh 'uname -a'
                print "s2: NODE_NAME = ${env.NODE_NAME}"
            }
        }
    }
}
