---
jobs:

- script: |
    job('uname') {
      label('agent1 || agent2')
      steps {
        shell('uname -a')
      }
    }

- script: |
    pipelineJob('jenkins2') {
      definition {
        cpsScm {
          scm {
            git {
              remote { url('https://github.com/sk4zuzu/RESEARCH.git') }
              branches('jenkins')
              scriptPath('jenkins_research/jenkins2/Jenkinsfile')
              extensions { }
            }
          }
        }
      }
    }
