---

- hosts: all
  gather_facts: true
  tasks: []

- hosts: wireguard_client
  roles:
    - role: wireguard-common

- hosts: wireguard_client
  serial: 1
  handlers:
    - import_tasks: roles/wireguard-common/handlers/main.yml
  roles:
    - role: wireguard-client

- hosts: nfs4_client
  roles:
    - role: nfs4-common
    - role: nfs4-client

# vim:ts=2:sw=2:et:syn=yaml:
