---

- hosts: all
  gather_facts: true
  tasks: []

- hosts: wireguard_server[0]
  roles:
    - role: wireguard-common
    - role: wireguard-server

- hosts: nfs4_server[0]
  roles:
    - role: nfs4-common
    - role: nfs4-server

# vim:ts=2:sw=2:et:syn=yaml:
