---

- hosts: 127.0.0.1
  become: false
  tasks:
    - vars:
        kek: kek
        lel: lel
        names:
          - 00-kek
          - 01-lel

      always:
        - &cleanup
          set_fact:
            rendered: []
            encrypted: {}
          no_log: true

      rescue:
        - fail:
            msg: "{{ ansible_failed_result }}"

      block:
        - *cleanup

        - set_fact:
            rendered: >-
              {{ rendered + [lookup('template', item ~ '.yml.j2')] }}
          loop: >-
            {{ names }}
          no_log: true

        - command: ansible-vault encrypt_string --stdin-name encrypted
          args:
            stdin: >-
              {{ _joined }}
          environment:
            ANSIBLE_VAULT_PASSWORD_FILE: "{{ playbook_dir }}/vault-password-file"
          register: encrypted
          vars:
            _joined: >-
              {{ rendered | map('from_yaml_all')
                          | map('select')
                          | map('list')
                          | flatten
                          | map('to_nice_yaml')
                          | join(_newline ~ '---' ~ _newline) }}
            _newline: "\n"
          no_log: true

        - vars:
            _extracted: >-
              {{ (encrypted.stdout | regex_replace('!vault', '') | from_yaml).encrypted }}
          block:
            - copy:
                dest: encrypted.yml
                content: >-
                  {{ _extracted }}
                decrypt: false
              no_log: true

            - shell: |
                # kubectl apply -f-
                cat
              args:
                stdin: >-
                  {{ _extracted }}
              #no_log: true

# vim:ts=2:sw=2:et:syn=yaml:
