---

- hosts: 127.0.0.1
  become: false
  tasks:
    - vars:
        kek: kek
        lel: lel
        names:
          - 00-kek
          - 01-lel

      always:
        - &cleanup
          set_fact:
            rendered: []
          no_log: true

      rescue:
        - fail:
            msg: "{{ ansible_failed_result }}"

      block:
        - *cleanup

        - set_fact:
            rendered: >-
              {{ rendered + [lookup('template', item ~ '.yml.j2')] }}
          loop: >-
            {{ names }}
          no_log: true

        - vars:
            _newline: "\n"
            joined: >-
              {{ rendered | map('from_yaml_all')
                          | map('select')
                          | map('list')
                          | flatten
                          | map('to_nice_yaml')
                          | join(_newline ~ '---' ~ _newline) }}
          block:
            - shell: |
                set -o errexit -o pipefail
                ansible-vault encrypt_string | sed '/^!vault/d' \
                                             | tr -d '[:blank:]' \
                                             > encrypted.yml
              args:
                executable: bash
                stdin: >-
                  {{ joined }}
              environment:
                ANSIBLE_VAULT_PASSWORD_FILE: "{{ playbook_dir }}/vault-password-file"
              no_log: true

            - shell: |
                # kubectl apply -f-
                cat
              args:
                stdin: >-
                  {{ joined }}
              #no_log: true

# vim:ts=2:sw=2:et:syn=yaml:
