---

- name: load apiserver config
  slurp:
    path: &path /etc/kubernetes/manifests/kube-apiserver.yaml
  register: result
  until: result is success
  retries: 69
  delay: 2

- name: save modified apiserver config
  copy:
    dest: *path
    content: >-
      {{ _decoded | combine(_update, recursive=true) | to_nice_yaml(indent=2) }}

  vars:
    # missing config line
    _line: "--encryption-provider-config=/etc/kubernetes/pki/etcd/etcd-encryption.conf"

    # parse yaml payload
    _decoded: >-
      {{ result.content | b64decode | from_yaml }}

    # convert spec.containers list to dict (dicts can be merged)
    _containers_dict: >-
      {{ range(_decoded.spec.containers | length) | zip(_decoded.spec.containers)
                                                  | list
                                                  | items2dict(key_name=0, value_name=1) }}

    # append parameter to command in first container
    _containers_dict_update:
      0:
        command: >-
          {{ _decoded.spec.containers.0.command + ([] if _line in _decoded.spec.containers.0.command else [_line]) }}

    # convert updated spec.containers dict back to list
    _containers_updated: >-
      {{ (_containers_dict | combine(_containers_dict_update, recursive=true)).values()
                           | list }}

    # prepare update for whole document
    _update:
      spec:
        containers: >-
          {{ _containers_updated }}

# vim:ts=2:sw=2:et:syn=yaml:
