---

- name: install docker
  vars:
    docker_ce_version_apt: "5:{{ DOCKER_CE_VERSION }}~3-0~ubuntu-bionic"
    containerd_io_version_apt: "{{ CONTAINERD_IO_VERSION }}-3"

  block:
    - name: import docker-ce repository gpg key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: add docker-ce repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      register: result
      until: result is success
      retries: 69
      delay: 2

    - name: install docker-ce
      apt:
        name:
          - "docker-ce={{ docker_ce_version_apt }}"
          - "docker-ce-cli={{ docker_ce_version_apt }}"
          - "containerd.io={{ containerd_io_version_apt }}"
        state: present
      register: result
      until: result is success
      retries: 69
      delay: 2

# vim:ts=2:sw=2:et:syn=yaml:
