global:
  resolve_timeout: 5m

route:
  group_by: [alertname]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 2m
  receiver: mailpit1

receivers:
  - name: mailpit1
    email_configs:
      - to: asd@asd.asd
        from: asd@alertmanager2.poc.svc
        hello: alertmanager2.poc.svc
        smarthost: mailpit1.poc.svc:1025
        require_tls: false
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: [alertname, dev, instance]
